# Generated by Django 6.0.3 on 2026-04-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('QUALIFIED', 'Qualified'), ('NEW', 'New'), ('CONVERTED', 'Converted'), ('CONTACTED', 'Contacted')], default='NEW', max_length=20),
        ),
    ]
