# Generated by Django 6.0.3 on 2026-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('CONTACTED', 'Contacted')], default='NEW', max_length=20),
        ),
    ]
