# Generated by Django 6.0.3 on 2026-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONVERTED', 'Converted'), ('QUALIFIED', 'Qualified'), ('CONTACTED', 'Contacted')], default='NEW', max_length=20),
        ),
    ]
