# Generated by Django 6.0.3 on 2026-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('CONTACTED', 'Contacted'), ('NEW', 'New')], default='NEW', max_length=20),
        ),
    ]
